### PR TITLE
Add back Slim template integration with lazy loading

### PR DESCRIPTION
**Pull request by minad**
See the discussion in https://github.com/slim-template/slim/issues/918

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for submitting this. This looks pretty good.  Please update `.ci.gemfile` so that the slim integration will get tested in CI.  In terms of slim's dependency on tilt, that would need to be fixed before the release of tilt 2.2.  I'm planning that in about 3 weeks.  Do you think a new version of slim can be released by then with the fixed dependency?

**Comment by minad** [comment]
> In terms of slim's dependency on tilt, that would need to be fixed before the release of tilt 2.2. I'm planning that in about 3 weeks. Do you think a new version of slim can be released by then with the fixed dependency?

**Comment by jeremyevans** [comment]
OK.  I guess I can wait a little longer, as long as it is before the end of May.

**Comment by minad** [comment]
Okay, sounds good. I updated the .ci.gemfile. The remaining test failure is unrelated to Slim.

**Comment by jeremyevans** [comment]
Took a few tries, but I fixed the Ruby 2.5 CI failure.  Can you rebase this on the master branch?

Note that even if CI passes for the versions, Ruby <2.5 users will not be able to use tilt 2.1+ with slim if tilt and slim are being loaded via rubygems, because slim versions that don't have the restrictive tilt dependency won't support older Ruby versions, and slim versions that support older Ruby versions have the restrictive tilt dependency.  I've seen this type of issue happen often enough that I avoid pessimistic dependency restrictions for libraries, unless I am 100% sure that a future version of the dependency will be incompatible.  I guess the good news is the population of affected users is not likely to be high.

**Comment by minad** [comment]
> Took a few tries, but I fixed the Ruby 2.5 CI failure. Can you rebase this on the master branch?

Done.

> Note that even if CI passes for the versions, Ruby <2.5 users will not be able to use tilt 2.1+ with slim if tilt and slim are being loaded via rubygems, because slim versions that don't have the restrictive tilt dependency won't support older Ruby versions, and slim versions that support older Ruby versions have the restrictive tilt dependency. I've seen this type of issue happen often enough that I avoid pessimistic dependency restrictions for libraries, unless I am 100% sure that a future version of the dependency will be incompatible. I guess the good news is the population of affected users is not likely to be high.

If the need arises, I can publish a backported minor version of Slim which lifts the Tilt dependency bounds.

**Pull request merged**
