### PR TITLE
Document use of StaticTemplate

### PR DESCRIPTION
**Pull request by adam12**

### CODE REVIEW

**Comment by adam12** [comment]
I'd like to add an `@example` if you're open to it Jeremy.

**Comment by jeremyevans** [comment]
Thanks for the patch! This looks good.  One of my eventual plans is to remove all yard tags and document everything with rdoc.  Could you add the example using rdoc?

**Comment by adam12** [comment]
Added a contrived example.

**Comment by jeremyevans** [comment]
Looks good.  Thanks!

**Pull request merged**
